config/routes.rb
Rails.application.routes.draw do

  get 'words' => 'words#word'
  get 'words/index' => 'words#index'
  resources :words

  get 'phrases' => 'phrases#phrase'
  get 'phrases/index' => 'phrases#index'
  resources :phrases
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  validates :phr_eng, uniqueness: true, presence: true
  validates :phr_rus, :examp, presence: true
end

app/models/word.rb
class Word < ApplicationRecord

  def self.search(search)
    where("eng LIKE ?", "#{search}") 
  end

  scope :by_range_id, -> id_from, id_to {where(id: id_from..id_to) if id_from.present? && id_to.present?}
  scope :by_first_letter, -> first_letter {where("substr(eng, 1, 1) in (#{first_letter})") if first_letter.present?}
  scope :by_latest_ids, -> end_ids {order("id desc").limit(end_ids) if end_ids.present?}

  validates :eng, :rus, :translation, presence: true
  validates :eng, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  
  def phrase
    @phrase = Phrase.order("RANDOM()").first
    @count = Phrase.all.length

    @date = @phrase.created_at.to_date.to_s.split('-')
    m = {'01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December'}
    m = m.select{|key| key == @date[1]}
    @date[1] = m.first[1]
    @date.slice!(2)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @phrase = Phrase.all
  end 

  def new
    @phrase = Phrase.new
  end

  def create
    @phrase = Phrase.new(phrase_params)
    if @phrase.save
      redirect_to phrases_path
    else
      render 'new'
    end
  end

  def edit
    @phrase = Phrase.find(params[:id])
    @count = Phrase.all.length
  end

  def update
    @phrase = Phrase.find(params[:id])

    if @phrase.update(phrase_params)
      redirect_to phrases_index_path
    else
      render 'edit'
    end
  end

  private
    def phrase_params
      params.require(:phrase).permit(:phr_eng, :phr_rus, :examp)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  include YandexDictionary

  has_scope :by_range_id, :using => [:id_to, :id_from], only: :word, :type => :hash
  has_scope :by_first_letter, :using => :first_letter, only: :word, :type => :hash
  has_scope :by_latest_ids, :using => :end_ids, only: :word, :type => :hash

  def word
    # offset = params[:offset].present? && params[:offset].to_i > 0 ? params[:offset] : 0
    gon.allWords = Word.all
    if params[:id_from].blank? && params[:id_to].blank? && params[:first_letter].blank? && params[:end_ids].blank?
      # @word = Word.order("RANDOM()").first
      gon.selectedWords = Word.all
    else
      # words = apply_scopes(Word.by_range_id(params[:id_from], params[:id_to]).by_first_letter(params[:first_letter]).by_latest_ids(params[:end_ids])).all
      gon.selectedWords = apply_scopes(Word.by_range_id(params[:id_from], params[:id_to]).by_first_letter(params[:first_letter]).by_latest_ids(params[:end_ids])).all
      # if params[:offset].to_i == words.length
      #   params[:offset] = 0
      # end
      # @word = words.offset(params[:offset].to_i).limit(1).first
    end

    @count = Word.all.length

    if params[:search]
      res = Word.search(params[:search])
      @word = res.first
    end

    # # @date = @word.created_at.to_date.to_s.split('-')
    # @date = gon.wordsJSON.created_at.to_date.to_s.split('-')
    # m = {'01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December'}
    # m = m.select{|key| key == @date[1]}
    # @date[1] = m.first[1]
    # @date.slice!(2)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @words = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)

    json_response = translate(@word.eng)
    
    if json_response['def'].present?
      rus = json_response['def'][0]['tr'][0]['text']

      translation = {}

      words = []

      json_response['def'].each do |i|
        i['tr'].each do |i|
          word_part = i['pos'].to_sym
          translation[word_part] = words.push(i['text'])
        end
        words = []
      end
    end

    @word = Word.new({ 'eng' => @word.eng.downcase, 'rus' => rus, 'translation' => translation })

    if @word.save
      redirect_to word_path(@word)
    else
      render 'new'
    end
  end
  
  def show
    @word = Word.find(params[:id])
    @count = Word.all.length
    @translation = JSON.parse(@word.translation.gsub(':','"').gsub('=>','":'))

    json_response = translate(@word.eng)

    res = []
    @examples = []

    json_response['def'].each do |i|
      i['tr'].each do |i|
        res.push(i['ex'])
      end
    end

    res.delete(nil)
    res = res.flatten(1)

    res.each do |i|
      @examples.push(i['text'])
    end
  end
  
  def edit
    @word = Word.find(params[:id])
    @count = Word.all.length
  end
  
  def update
    @word = Word.find(params[:id])

    if @word.update(word_params)
      redirect_to words_index_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to words_index_path
  end

  private
    def word_params
      params.require(:word).permit(:eng, :rus, :translation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title English
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = include_gon
    = javascript_include_tag 'http://code.responsivevoice.org/responsivevoice.js', 'data-turbolinks-track': true
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.png'
  body
    = yield

app/views/phrases/_form_edit.html.slim
= form_for @phrase do |f| 
  table
    tr class='tr-edit'
      td
        = f.label :'Original phrase', class: 'edit-label'
      td
        = f.text_field :phr_eng, class: 'edit-field'
      tr class='tr-edit'
        td
          = f.label :'Russian translate', class: 'edit-label'
        td
          = f.text_field :phr_rus, class: 'edit-field'
      tr class='tr-edit'
        td
          = f.label :'Example', class: 'edit-label'
        td
          = f.text_field :examp, class: 'edit-field'
      tr
        td
          = f.submit :'CONFIRM', class: 'editing-button'

app/views/phrases/_form_new.html.slim
= form_for @phrase do |f| 
  br
  = f.text_field :phr_eng, class: 'create-phrase-eng', :autofocus=>true, placeholder: "Phrase"
  br
  = f.text_field :phr_rus, class: 'create-phrase-eng', placeholder: "Translate"
  br
  = f.text_field :examp, class: 'create-phrase-eng', placeholder: "Example"
  br
  = f.submit :'NEW', class: 'create-button'

div.error-msg
  = @phrase.errors.full_messages.first if @phrase.errors.any?

app/views/phrases/_random_phrase.html.slim
p.created-at This phrase was added at #{@date[1]} #{@date[0]}
div.window-phrase 
  p.phrase-examp #{phrase.examp}
  p.phrase-eng #{phrase.phr_eng}
  div.hide-rus-phrase show
  p.phrase-rus #{phrase.phr_rus}
div.next-phrase-div
  = link_to "Next", phrases_path, :remote => true, class: 'get-phrase'

app/views/phrases/_upper_menu.html.slim
= link_to 'All phrases', phrases_index_path, class: 'REST-links'
= link_to 'Add phrase', new_phrase_path, class: 'REST-links'
= link_to 'Edit phrase', edit_phrase_path(phrase), class: 'REST-links', id: 'REST-edit'
= link_to 'x',  phrases_path(phrase),
                          method: :delete, 
                          data: { confirm: 'Are you sure?' },
                          class: 'REST-links'
= link_to_if phrases_path, 'To google', 'https://translate.google.ru/#en/ru/' + @phrase.phr_eng, class: 'to-google', :target => '_blank'
= link_to 'Go over to words', words_path, class: 'to-words'

app/views/phrases/edit.html.slim
div.upper-nav 
  span.REST-links Editing phrase
= link_to 'Back', phrases_path, class: 'back-link'
= render 'form_edit'

app/views/phrases/index.html.slim
div.upper-nav 
  span.REST-links My phrases
= link_to 'Back', phrases_path, class: 'back-link'
span.info-count You know #{@phrase.length} phrases
div.scroll-index-word
  table.index-word-table
    tr.info-word-index
    - @phrase.each do |phrase| 
      tr.info-word-index
      td.part-of-speech-td-index #{phrase.phr_eng}
      td.part-of-speech-translate-td-index #{phrase.phr_rus}
      td.index-rest = link_to 'Edit', edit_phrase_path(phrase), class: 'index-rest'
      td.index-rest = link_to 'Delete',  phrase_path(phrase),
                              class: 'index-rest',
                              method: :delete, 
                              data: { confirm: 'Are you sure?' }

app/views/phrases/new.html.slim
div.upper-nav 
  span.REST-links New phrase
= link_to 'Back', @phrase, class: 'back-link'
div.content-new
  = render 'form_new'

app/views/phrases/phrase.html.slim
div.upper-nav
  = render partial: 'upper_menu', locals: { phrase: @phrase }
/ div.under-nav-info
div.under-nav
  span.info-count You know #{@count} phrases
.content-word
  = render partial: 'random_phrase', locals: { phrase: @phrase }

app/views/phrases/phrase.js.erb
$(".content-word").html("<%= j  (render partial: 'random_phrase', locals: { phrase: @phrase } ) %>"); 
$(".upper-nav").html("<%= j  (render partial: 'upper_menu', locals: { phrase: @phrase } ) %>"); 
$('.phrase-rus').hide();
hideRusPhrase = $(".hide-rus-phrase");
hideRusPhrase.on('click', function () {
  $(hideRusPhrase).hide();
  $('.phrase-rus').show();
});

app/views/words/_form_edit.html.slim
= form_for @word do |f| 
  table class='edit-table'
    tr class='tr-edit'
      td
        = f.label :eng, class: 'edit-label'
      td
        = f.text_field :eng, class: 'edit-field'
      tr class='tr-edit'
        td
          = f.label :rus, class: 'edit-label'
        td
          = f.text_field :rus, class: 'edit-field'
      tr class='tr-edit'
        td
          = f.label :translation, class: 'edit-label'
        td
          = f.text_field :translation, class: 'edit-field'
      tr
        td
          = f.submit :'CONFIRM', class: 'edit-button'

app/views/words/_form_new.html.slim
= form_for @word do |f|
  br
  = f.text_field :eng, class: 'create-field', :autofocus=>true
  br
  = f.submit :'NEW', class: 'create-button'

div.error-msg
  = @word.errors.full_messages.first if @word.errors.any?

app/views/words/_form_search.html.slim
div.sidebar-content
  div.sidebar-search
    = form_tag(words_path, :method => "get", id: "search-form", :remote => true) do
      p = text_field_tag :search, params[:search], placeholder: "Word", class: 'params-field-search'
      p = submit_tag "Search", :name => nil, class: 'button-search', :onclick => 'searchWord()'
  div.sidebar-params 
    = form_tag(words_path, :method => "get", id: "words-param-form") do
      p.label-f
        = label_tag 'Set range', nil, class: 'label-search'
      p.range-f
        = text_field_tag :id_from, params[:id_from], placeholder: "1", class: 'params-field-range'
        = text_field_tag :id_to, params[:id_to], placeholder: "100", class: 'params-field-range'
      p.label-f
        = label_tag 'Take recent words', nil, class: 'label-search'
      p.recent-f
        = text_field_tag :end_ids, params[:end_ids], placeholder: "100", class: 'params-field'
      p.label-f
        = label_tag 'Starting with', nil, class: 'label-search'
      p.letters-f
        = text_field_tag :first_letter, params[:first_letter], placeholder: "a, b, c", class: 'params-field'
        = hidden_field_tag :offset, 0
      p.apply-b = submit_tag "Apply", :name => nil, class: 'button-search'
    = link_to 'Reset', words_path, class: 'button-search'

app/views/words/_part_of_speech.html.slim
 div.show-content
  table.show-word-table
    tr.show-tr-word
      td.show-eng onclick='voiceText(this)' #{@word.eng.capitalize}
      td.show-rus #{@word.rus.mb_chars.capitalize.to_s}

    - @translation.each do |key|
      tr.show-tr
        td.show-part-of-speach-td #{key[0].capitalize} 
        td.show-translation-td
          - key[1].each do |i|
            - if i == key[1].last
              = i
            - else 
              = i + ", "
                  
    tr.show-tr
      td.examples-td colspan='2'
        - if @examples.empty?
          p No examples, sorry
        - @examples.each do |i|
          - if i == @examples.last
            = i.capitalize
          - else
            = i.capitalize + ", "

app/views/words/_random_word.html.slim
div.window-word  
  = image_submit_tag ("volume.png"), class: 'voice', onclick: 'voiceText()'
  div.eng-field
    span.word-eng
  div.rus-field
    div.hide-rus
    span.word-rus 
div.next-word-div
  = link_to "Next", words_path(:id_from => params[:id_from], :id_to => params[:id_to], :first_letter => params[:first_letter], :end_ids => params[:end_ids], :offset => params[:offset].to_i + 1), :remote => true, class: 'get-word', :onclick => 'countWatchedWords(), setMethod()'
div.footer
  //span.created-at This word was added at #{@date[1]} #{@date[0]}
  span.created-at

app/views/words/_upper_menu.html.slim
/ = link_to 'LIST', words_index_path, class: 'REST-links'
/ = link_to 'ADD', new_word_path, class: 'REST-links'
/ = link_to 'EDIT', edit_word_path(word), class: 'REST-links', id: 'REST-edit'
/ = link_to 'MORE', word_path(word), class: 'REST-links', id: 'REST-show'
/ = link_to 'X',  word_path(word),
/                             method: :delete, 
/                             data: { confirm: 'Are you sure?' },
/                             class: 'REST-links'
/ = link_to image_tag('google.png', class: 'to-google'), 'https://translate.google.ru/#en/ru/' + @word.eng, :target => '_blank'
/ = link_to 'PHRASES', phrases_path, class: 'to-phrases'

//delete it if I will want to return back lol
= link_to 'LIST', 'http://localhost:3000/words/index', class: 'REST-links', :target => '_blank'
= link_to 'ADD', 'http://localhost:3000/words/new', class: 'REST-links', :target => '_blank'
= link_to 'EDIT', 'http://localhost:3000/words/?/edit', class: 'REST-links', id: 'REST-edit', :target => '_blank'
= link_to 'MORE', 'http://localhost:3000/words/?', class: 'REST-links', id: 'REST-show', :target => '_blank'
= link_to 'X',  'http://localhost:3000/words/?',
                            method: :delete, 
                            data: { confirm: 'Are you sure?' },
                            class: 'REST-links',
                            id: 'REST-delete'
= link_to image_tag('google.png', class: 'to-google'), 'https://translate.google.ru/#en/ru/', :target => '_blank'
= link_to 'PHRASES', phrases_path, class: 'to-phrases'
//end

app/views/words/edit.html.slim
div.upper-nav 
  span.REST-links EDIT
div.under-nav
  = link_to 'BACK', words_path, class: 'back-link'
= render 'form_edit'

app/views/words/index.html.slim
div.upper-nav 
  span.REST-links LIST
div.under-nav
  = link_to 'BACK', words_path, class: 'back-link'
  span.sc SCROLL TO: 
  = tag "input", { "type" => "button", "value" => "END", "onclick" => "scrollTableEvent.smoothToBottom()", 'class' => 'scrolls'} 
  = tag "input", { "type" => "button", "value" => "TOP", "onclick" => "scrollTableEvent.smoothToTop()", 'class' => 'scrolls'}
  span.sc OR
  = tag "input", { "type" => "text", 'class' => 'scroll-id', 'placeholder' => 'ID', 'id' => 'scroll-id'}
  = tag "input", { "type" => "button", "value" => "GO", "onclick" => "scrollTableEvent.smoothToId(document.getElementById('scroll-id').value)", 'class' => 'scrolls'}
div.index-scroll-word
  table.index-word-table cellpadding="15"
    - @words.each do |words| 
      tr.index-tr id=words.id
        td.index-eng #{words.eng.upcase}
        td.index-rus #{words.rus.mb_chars.upcase.to_s}
        td.index-rest-td = link_to 'M', word_path(words), class: 'index-rest-td-a'
        td.index-rest-td = link_to 'E', edit_word_path(words), class: 'index-rest-td-a'
        td.index-rest-td = link_to 'X',  word_path(words),
                                class: 'index-rest-td-a',
                                method: :delete, 
                                data: { confirm: 'Are you sure?' }

app/views/words/new.html.slim
div.upper-nav 
  span.REST-links ADD
div.under-nav
  = link_to 'BACK', @word, class: 'back-link'
div.content-new
  = render 'form_new'

app/views/words/show.html.slim
div.upper-nav 
  span.REST-links MORE
div.under-nav
  = link_to 'BACK', words_path, class: 'back-link'
  = link_to 'NEW WORD', new_word_path, class: 'back-new-link'
div.content-meanings
  = render partial: 'part_of_speech'

app/views/words/word.html.slim
div.upper-nav
  = render partial: 'upper_menu', locals: { word: @word }
div.content
  div.under-nav
    = image_tag ('search.png'), class: 'options-search-button', :remote => true
    span.info-views 
    span.info-count You know #{@count} words
  = render partial: 'form_search'
  div.content-word
    = render partial: 'random_word', locals: { word: @word }
    

app/views/words/word.js.erb
// $(".content-word").html("<%= j  (render partial: 'random_word', locals: { word: @word } ) %>"); 
// $(".upper-nav").html("<%= j  (render partial: 'upper_menu', locals: { word: @word } ) %>"); 

// hideRus = $(".hide-rus");
// rusField = $('.rus-field');

// hideRus.height(rusField.outerHeight());

// hideRus.on('click', function () {
//   $(hideRus).fadeOut(350);
// });